version: '3'
services:
  nginx:
    image: nginx:mainline
    volumes:
      - 'wordpress:/usr/src/wordpress:ro'
      - './wp-content:/var/www/html/wp-content:ro'
      - './etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - front
    ports:
      - 8000:8000
      - 8443:8443

  php:
    image: joshbetz/wordpress
    volumes:
      - 'wordpress:/usr/src/wordpress:ro'
      - './wp-content:/var/www/html/wp-content:rw'
      - './wp-config:/var/www/html/wp-config:ro'
    networks:
      - front
      - back
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - MYSQL_PASSWORD=password
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_AUTH_KEY=
      - WORDPRESS_SECURE_AUTH_KEY=
      - WORDPRESS_LOGGED_IN_KEY=
      - WORDPRESS_NONCE_KEY=
      - WORDPRESS_AUTH_SALT=
      - WORDPRESS_SECURE_AUTH_SALT=
      - WORDPRESS_LOGGED_IN_SALT=
      - WORDPRESS_NONCE_SALT=

  cli:
    image: joshbetz/wordpress:cli
    command: bash -c 'while sleep 300; do wp cron event run --due-now; done'
    volumes:
      - 'wordpress:/usr/src/wordpress:ro'
      - './wp-content:/var/www/html/wp-content:rw'
      - './wp-config:/var/www/html/wp-config:ro'
    networks:
      - back
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - MYSQL_PASSWORD=password
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_AUTH_KEY=
      - WORDPRESS_SECURE_AUTH_KEY=
      - WORDPRESS_LOGGED_IN_KEY=
      - WORDPRESS_NONCE_KEY=
      - WORDPRESS_AUTH_SALT=
      - WORDPRESS_SECURE_AUTH_SALT=
      - WORDPRESS_LOGGED_IN_SALT=
      - WORDPRESS_NONCE_SALT=

  memcached:
    image: memcached
    networks:
      - back

  mysql:
    image: mariadb:10.6
    networks:
      - back
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password

  mailhog:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:8025:8025
    networks:
      - back

networks:
  front:
  back:

volumes:
  wordpress:
